---
- name: Execute preflight tasks
  ansible.builtin.include_tasks: preflight.yml
  when: kubernetes_role == "control_plane"

- name: Builds and installs Slurm-operator images
  ansible.builtin.include_tasks: images.yml
  when: slinky_build_images

- name: Configures slurm-operator Helm chart
  ansible.builtin.include_tasks: slurm-operator.yml
  when: kubernetes_role == "control_plane"

- name: Configures slurm Helm chart
  ansible.builtin.include_tasks: slurm.yml
  when: kubernetes_role == "control_plane"

- name: Configures slurm-bridge Helm chart
  ansible.builtin.include_tasks: slurm-bridge.yml
  when: kubernetes_role == "control_plane"