---
- name: Execute preflight tasks
  ansible.builtin.include_tasks: preflight.yml

- name: Configures slurm-operator Helm chart
  ansible.builtin.include_tasks: slurm-operator.yml

# TODO Confirm operator is installed
# TODO This isn't creating the proper replica count of compute nodes
- name: Configures Slurm Helm chart
  kubernetes.core.helm:
    name: "{{ slurm_chart_name }}"
    chart_ref: "{{ slurm_chart_ref }}"
    namespace: "{{ slurm_chart_namespace }}"
    create_namespace: true
    state: "{{ slurm_chart_state }}"
    values: "{{ slurm_chart_values }}"
  retries: 2
  delay: 5
  register: slurm_chart

- name: Configures slurm-bridge
  ansible.builtin.include_tasks: slurm-bridge.yml
