---
- name: Execute preflight tasks
  ansible.builtin.include_tasks: preflight.yml

- name: Configures slurm-operator Helm chart
  ansible.builtin.include_tasks: slurm-operator.yml

# TODO Confirm operator is installed
- name: Configures Slurm Helm chart
  when: install_slurm_chart
  kubernetes.core.helm:
    name: slurm
    chart_ref: "oci://ghcr.io/slinkyproject/charts/slurm"
    namespace: slurm
    create_namespace: true
    state: "{{ slurm_chart_state }}"
    values: "{{ slurm_chart_values }}"
  retries: 2
  delay: 5

- name: Configures slurm-bridge
  ansible.builtin.include_tasks: slurm-bridge.yml