---
- name: Configure a nfs StorageClass
  when: (storage_exists.resources == [])
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: "{{ api_version }}"
      kind: StorageClass
      metadata:
        name: "standard"
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: "kubernetes.io/no-provisioner"
      parameters:
        server: "{{ nfs_server }}"
        path: "{{ nfs_path }}"
        readOnly: "{{ nfs_read_only }}"
  register: storage_exists