---
- name: Add helm repos for local dependencies
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    repo_state: "{{ item.state }}"
  loop: "{{ slurm_operator_repo_dependencies }}"

# - name: Install helm charts
#   ansible.builtin.include_tasks: chart.yml
#   loop:
#     - {name: cert-manager, chart_ref: "jetstack/cert-manager", namespace: cert-manager, force: true, values: }

- name: Apply cert-manager Helm Chart
  kubernetes.core.helm:
    update_repo_cache: true
    name: cert-manager
    chart_ref: jetstack/cert-manager
    namespace: cert-manager
    create_namespace: true
    force: true # This is necessary because the default idempotency check is not sufficient to detect changes to set_values
    set_values:
      - value: crds.enabled=true
  retries: 2
  delay: 5

- name: Apply prometheus Helm Chart
  kubernetes.core.helm:
    update_repo_cache: true
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    namespace: prometheus
    create_namespace: true
  retries: 2
  delay: 5

- name: Apply Operator Helm Chart
  kubernetes.core.helm:
    name: "{{ slurm_operator_chart_name }}"
    chart_ref: "{{ slurm_operator_chart_ref }}"
    namespace: "{{ slurm_operator_chart_namespace }}"
    create_namespace: true
    state: "{{ slurm_operator_chart_state }}"
  retries: 2
  delay: 5