---
- name: Confirm operator is present before attempting to initialize Slurm
  tags: configure
  ansible.builtin.assert:
    that:
      - slurm_operator_chart_state == "present"
    fail_msg: "'slurm_operator_chart_state' must be 'present' when 'slurm_chart_state' is 'present'"
    success_msg: "'slurm-operator chart is not absent while slurm chart is present'"
  when: slurm_chart_state == "present"

- name: Configures Slurm Helm chart
  tags: configure
  kubernetes.core.helm:
    name: "{{ slurm_chart_name }}"
    chart_ref: "{{ slurm_chart_ref }}"
    chart_version: "{{ slurm_operator_chart_version }}"
    namespace: "{{ slurm_chart_namespace }}"
    create_namespace: true
    state: "{{ slurm_chart_state }}"
    values_files: "{{ slinky_chart_dir }}/slurm-operator/helm/slurm/values.yaml"
  retries: 2
  delay: 5
  register: slurm_chart

- name: Remove PVC's from Slurm NS # As far as I can tell, this can't be done with kubernetes.core.k8s
  when: slurm_chart.changed and slurm_chart_state == "absent" and slinky_devel
  ansible.builtin.command:
    cmd: "kubectl delete pvc -n slurm --all"
  changed_when: true
