---
# TASK REF: https://github.com/SlinkyProject/slurm-operator?tab=readme-ov-file#installation
- name: Add helm repos for local dependencies
  tags: install
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    repo_state: "{{ item.state }}"
  loop: "{{ slurm_operator_chart_dependencies }}"

- name: Apply cert-manager Helm Chart
  tags: install
  kubernetes.core.helm:
    update_repo_cache: true
    name: cert-manager
    chart_ref: jetstack/cert-manager
    namespace: cert-manager
    create_namespace: true
    set_values:
      - value: crds.enabled=true
  retries: 2
  delay: 5

- name: Apply prometheus Helm Chart
  tags: install
  kubernetes.core.helm:
    update_repo_cache: true
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    namespace: prometheus
    create_namespace: true
  retries: 2
  delay: 5

- name: Apply Operator Helm Chart
  tags: configure
  kubernetes.core.helm:
    name: "{{ slurm_operator_chart_name }}"
    chart_ref: "{{ slurm_operator_chart_ref }}"
    chart_version: "{{ slurm_operator_chart_version }}"
    namespace: "{{ slurm_operator_chart_namespace }}"
    create_namespace: true
    state: "{{ slurm_operator_chart_state }}"
    values_files: "{{ slinky_chart_dir }}/slurm-operator/helm/slurm-operator/values.yaml"
  retries: 2
  delay: 5
