# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

#
# -- (string)
# Overrides the name of the release.
nameOverride: ""

#
# -- (string)
# Overrides the full name of the release.
fullnameOverride: ""

#
# -- (string)
# Overrides the namespace of the release.
namespaceOverride: ""

#
# Default values for slurm-bridge.
scheduler:
  #
  # Set the image to use.
  image:
    #
    # -- (string)
    # Set the image repository to use.
    repository: ghcr.io/slinkyproject/slurm-bridge-scheduler
    #
    # -- (string)
    # Set the image tag to use.
    # @default -- The Release appVersion.
    tag: ""
  #
  # -- (integer)
  # Set the number of replicas to deploy.
  replicaCount: 1
  #
  # -- (bool)
  # Enables leader election.
  leaderElect: false
  #
  # -- (string)
  # Set the priority class to use.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
  priorityClassName: ""
  #
  # -- (object)
  # Set container resource requests and limits for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 1Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
  nodeSelector: {}
  #
  # -- (object)
  # Set affinity for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  #
  # -- (list)
  # Configure pod tolerations.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
  #
  # -- (integer)
  # Set the verbosity level of the scheduler.
  verbosity: null

#
# Configuration settings for the scheduler.
schedulerConfig:
  #
  # -- (string)
  # Set the name of the scheduler.
  schedulerName: slurm-bridge-scheduler
  #
  # -- (string)
  # Set the Slurm MCS Label to use for placeholder jobs.
  # Ref: https://slurm.schedmd.com/sbatch.html#OPT_mcs-label
  mcsLabel: kubernetes
  #
  # -- (string)
  # Set the default Slurm partition to use for placeholder jobs.
  # Ref: https://slurm.schedmd.com/sbatch.html#OPT_partition
  partition: slurm-bridge

#
# Configuration settings for the admission controller.
admission:
  #
  # -- (bool)
  # Enables admission controller.
  enabled: true
  #
  # Set the image to use.
  image:
    #
    # -- (string)
    # Set the image repository to use.
    repository: ghcr.io/slinkyproject/slurm-bridge-admission
    #
    # -- (string)
    # Set the image tag to use.
    # @default -- The Release appVersion.
    tag: ""
  #
  # Cert-Manager certificate configurations.
  certManager:
    #
    # -- (bool)
    # Enables cert-manager for certificate management.
    enabled: true
    #
    # -- (string)
    # Duration of certificate life.
    duration: 43800h0m0s # 5 year
    #
    # -- (string)
    # Certificate renewal time. Should be before the expiration.
    renewBefore: 8760h0m0s # 1 year
  #
  # -- (integer)
  # Set the number of replicas to deploy.
  replicas: 1
  #
  # -- (string)
  # Set the priority class to use.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
  priorityClassName: ""
  #
  # -- (object)
  # Set container resource requests and limits for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 1Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
  nodeSelector: {}
  #
  # -- (object)
  # Set affinity for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  #
  # -- (list)
  # Configure pod tolerations.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
  #
  # -- (list)
  # List of namespaces to be monitored by the pod admission controller.
  # Pods created in any of these namespaces will have their `.spec.schedulerName`
  # changed to slurm-bridge.
  managedNamespaces: []
    # - managedNamespace1
    # - managedNamespace2

#
# Configuration settings for the controllers.
controllers:
  #
  # Set the image to use.
  image:
    #
    # -- (string)
    # Set the image repository to use.
    repository: ghcr.io/slinkyproject/slurm-bridge-controllers
    #
    # -- (string)
    # Set the image tag to use.
    # @default -- The Release appVersion.
    tag: ""
  #
  # -- (integer)
  # Set the number of replicas to deploy.
  replicas: 1
  #
  # -- (string)
  # Set the priority class to use.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
  priorityClassName: ""
  #
  # -- (object)
  # Set container resource requests and limits for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 1Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
  nodeSelector: {}
  #
  # -- (object)
  # Set affinity for Kubernetes Pod scheduling.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  #
  # -- (list)
  # Configure pod tolerations.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
  #
  # -- (integer)
  # Set the verbosity level of the controllers.
  verbosity: null

#
# Configurations shared among all components.
sharedConfig:
  #
  # -- (string)
  # The Slurm REST API URL in the form of: `[protocol]://[host]:[port]`
  slurmRestApi: http://slurm-restapi.slurm:6820
  #
  # -- (string)
  # The secret containing a SLURM_JWT token for authentication.
  slurmJwtSecret: slurm-bridge-jwt-token
